services:
  mongodb:
    image: mongo:4.4.26
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - "mongo_data:/data/db"
    networks:
      - app_network
  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - /.env
    depends_on:
      - mongodb
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
   mongo_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: ./data
